## NUMPY


In [1]:
import numpy as np

## Creating Array from List

In [10]:
arr_1d = np.array([1,2,3,4])
print("1D Array :", arr_1d) 

arr_2d = np.array([[1,2,3,4] , [5,6,7,8]])
print("2D Array :",  arr_2d) 

1D Array : [1 2 3 4]
2D Array : [[1 2 3 4]
 [5 6 7 8]]


## List vs Numpy Array

In [29]:
# Simple Python 
py_list = [1,2,3,4]
print("Multipication of List is", py_list * 2)

# In Numpy 
np_array = np.array([1,2,3,4])   # element vise multiplication
print("Multipication of Array is", np_array * 2)

import time 
start = time.time()
py_list = [i*2 for i in range(100000)]
print("The time taken to multiply list is :" , time.time() - start)

strat = time.time()
np_array = np.arange(100000) * 2   # arange is used to give range
print("The time taken to multipy numpy array is :" , time.time() - start)




Multipication of List is [1, 2, 3, 4, 1, 2, 3, 4]
Multipication of Array is [2 4 6 8]
The time taken to multiply list is : 0.00958395004272461
The time taken to multipy numpy array is : 0.010674715042114258


## Creating Array from scratch

In [40]:
# zero Array
zeros = np.zeros((3,4))
print("zeros array :\n", zeros)

# Ones Array
ones = np.ones((3,4))
print("zeros array :\n", ones)

# For specific constant 
full = np.full((2,2) ,10)
print("Full array :\n", full)

# Random 
random = np.random.random((2,3))
print("random array :\n", random)

# Sequence Array
sequence = np.arange(0 , 10 , 2)
print("sequence array :\n" , sequence)

zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros array :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array :
 [[10 10]
 [10 10]]
random array :
 [[0.64079959 0.48306636 0.45996374]
 [0.96238695 0.16245541 0.99070526]]
sequence array :
 [0 2 4 6 8]


## Vector , Matrix , Tensor

In [ ]:
# vector 
vector = np.array([1,2,3,4])
print("Vector:\n " , vector)

# matrix 
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:\n " , matrix)

# Tensor
tensor = np.array([[[1,2,3], [4,5,6]],
                   [[7,8,9], [1,1,1]]])
print("Tensor:\n " , tensor)


Vector:
  [1 2 3 4]
Matrix:
  [[1 2 3]
 [4 5 6]]
Tensor:
  [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 1 1]]]
3


## Array Properties

In [48]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape:", arr.shape)
print("dimension:", arr.ndim)
print("size:", arr.size)
print("datatype:", arr.dtype)



shape: (2, 3)
dimension: 2
size: 6
datatype: int64


## Array Reshaping

In [57]:
arr = np.arange(12)
print("Array :" , arr)

reshaped = arr.reshape((3,4))
print("Reshaped :" , reshaped)

flattened = reshaped.flatten()
print("Flattened : " ,flattened)

raveled = reshaped.ravel()  # returned view instead of copy
print("Raveled : " ,raveled)

transpose = reshaped.T
print("Transpose : " , transpose)


Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Array Join

In [58]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Array split

In [59]:


arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
