## Numpy Array Operation

In [2]:
import numpy as np

In [6]:
arr = np.arange(11)
print(arr[1:3])
print(arr[0:5:2])
print(arr[-3])

[1 2]
[0 2 4]
8


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element :" , arr_2d[1,2])
print("entire row :" , arr_2d[0])
print("entire row specific column :" , arr_2d[:,1])  # ':' means entire row 

specific element : 6
entire row : [1 2 3]
entire row specific column : [2 5 8]
specific element : 6


In [21]:
unsortes_array = np.array([3,6,2,8,34,78,9])
print("sorted array :" ,np.sort(unsortes_array))

unsorted_2d_array = np.array([[3,63,7],
                              [88,1,99],
                              [55,89,66]])
print("original array :\n",unsorted_2d_array)
print("2D sorted array :\n", np.sort(unsorted_2d_array))
print("2D column sorted array :\n", np.sort(unsorted_2d_array , axis=0))
print("2D row sorted array :\n", np.sort(unsorted_2d_array , axis=1))


sorted array : [ 2  3  6  8  9 34 78]
original array :
 [[ 3 63  7]
 [88  1 99]
 [55 89 66]]
2D sorted array :
 [[ 3  7 63]
 [ 1 88 99]
 [55 66 89]]
2D column sorted array :
 [[ 3  1  7]
 [55 63 66]
 [88 89 99]]
2D row sorted array :
 [[ 3  7 63]
 [ 1 88 99]
 [55 66 89]]


## Filter Array


In [23]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers are : ",even_number)

Even numbers are :  [ 2  4  6  8 10]


## Filter with mask 

In [24]:
mask = numbers > 5
print("Numbers greater than 5 is : " , numbers[mask])

Numbers greater than 5 is :  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [28]:
indices = [ 2,3,9]
print(numbers)
print(numbers[indices])  # It will enter the numbers at position 2,3,9

where_result = np.where(numbers>5)
print(numbers[where_result])

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  4 10]
[ 6  7  8  9 10]


In [29]:
condition_array = np.where(numbers > 5 , numbers * 2 , numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing the data

In [ ]:
# Adding 
original_array = np.array([[1,2,3], [4,5,6]])
new_row = np.array([[7,8,9]])

with_new_row = np.vstack((original_array , new_row))
print("original array : \n",original_array)
print("full array : \n" ,with_new_row)

new_column = np.array([[0],[0]])
with_new_column = np.hstack((original_array , new_column))
print("full array : \n" ,with_new_column)


original array : 
 [[1 2 3]
 [4 5 6]]
full array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
full array : 
 [[1 2 3 0]
 [4 5 6 0]]


In [44]:
# removing
arr = np.array([1,2,3,4,5,6,7,8])
deleted = np.delete(arr , 3 )
print(deleted)

[1 2 3 5 6 7 8]
